name: CI Pipeline

on:
  push:
    branches: [master, dev, ignite-engine]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-2025-vs2026
    strategy:
      matrix:
        configuration: [Release]
    env:
      VS_VERSION: "2026"
      SLNX_FILE: MochiSharp.slnx
      PREMAKE_VERSION: 5.0.0-beta8

    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup .NET 10 SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v3

      - name: Install Premake
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $version = "${{ env.PREMAKE_VERSION }}"
          $zipUrl = "https://github.com/premake/premake-core/releases/download/v$version/premake-$version-windows.zip"
          $dst = "$PWD/tools"
          New-Item -ItemType Directory -Force -Path $dst | Out-Null
          $zipPath = "$dst/premake.zip"
          Invoke-WebRequest -Uri $zipUrl -OutFile $zipPath
          Expand-Archive -Path $zipPath -DestinationPath $dst -Force
          "$dst" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: Generate Solution with Premake5
        shell: pwsh
        run: premake5 vs${{ env.VS_VERSION }} --file="premake5.lua"
      
      - name: Restore NuGet packages
        shell: pwsh
        run: msbuild $env:SLNX_FILE /t:Restore /p:Configuration=${{ matrix.configuration }} /p:Platform="x64"

      - name: Build Visual Studio
        shell: pwsh
        run: msbuild $env:SLNX_FILE /t:Rebuild /p:Configuration=${{ matrix.configuration }} /p:Platform="x64"
